version: '3.8'

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - custom_network
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "imok" ]
      interval: 30s
      timeout: 10s
      retries: 3

  scylla-node1:
    image: scylladb/scylla
    container_name: scylla-node1
    restart: on-failure
    privileged: true
    volumes:
      - scylla-data1:/var/lib/scylla/data
      - scylla-commitlog1:/var/lib/scylla/commitlog
      - ./scylla-node1.yaml:/conf/scylla.yaml
      - ./init_scylla.sh:/init_scylla.sh
    entrypoint: [ "/bin/bash", "/init_scylla.sh" ]
    command: "--overprovisioned 1"#"--smp 2 --memory 4G "#--overprovisioned 1"
    networks:
      - custom_network
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status || exit 1" ]
      interval: 30s
      timeout: 60s
      retries: 10

  scylla-node2:
    image: scylladb/scylla
    container_name: scylla-node2
    privileged: true
    volumes:
      - scylla-data2:/var/lib/scylla/data
      - scylla-commitlog2:/var/lib/scylla/commitlog
      - ./scylla-node2.yaml:/conf/scylla.yaml
      - ./init_scylla.sh:/init_scylla.sh
    entrypoint: [ "/bin/bash", "/init_scylla.sh" ]
    command: "--overprovisioned 1"#"--smp 2 --memory 4G "#--overprovisioned 1"
    networks:
      - custom_network
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status || exit 1" ]
      interval: 30s
      timeout: 60s
      retries: 10

  scylla-node3:
    image: scylladb/scylla
    container_name: scylla-node3
    privileged: true
    volumes:
      - scylla-data3:/var/lib/scylla/data
      - scylla-commitlog3:/var/lib/scylla/commitlog
      - ./scylla-node3.yaml:/conf/scylla.yaml
      - ./init_scylla.sh:/init_scylla.sh
    entrypoint: [ "/bin/bash", "/init_scylla.sh" ]
    command: "--overprovisioned 1"#"--smp 2 --memory 4G "#--overprovisioned 1"
    networks:
      - custom_network
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status || exit 1" ]
      interval: 30s
      timeout: 60s
      retries: 10

  postgres:
    image: postgres
    command: ["postgres", "-c", "port=5431"]
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: metadataDB
    ports:
      - '5431:5431'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - custom_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d metadataDB -p 5431" ]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.11.1
    environment:
      - "discovery.type=single-node"
      - "http.port=9205"
      - "xpack.security.enabled=false"  # Disable xpack security
      - "xpack.security.http.ssl.enabled=false"  # Disable HTTPS
    ports:
      - "9205:9205"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - custom_network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9205/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 35s
      retries: 5


  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9091:9091'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - custom_network
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server=localhost:9091 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - custom_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  log-ingestor:
    build:
      context: ./Backend/log-ingestor
    ports:
      - "3000:3000"
    volumes:
      - ./Backend/log-ingestor:/usr/src/myapp
    networks:
      - custom_network
    depends_on:
      postgres:
        condition: service_healthy
      scylla-node1:
        condition: service_healthy
      scylla-node2:
        condition: service_healthy
      scylla-node3:
        condition: service_healthy
      kafka:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy


  query-interface:
    build:
      context: ./Backend/query-interface
    ports:
      - "4000:4000"
    volumes:
      - ./Backend/query-interface:/usr/src/myapp
    networks:
      - custom_network
    depends_on:
      postgres:
        condition: service_healthy
      scylla-node1:
        condition: service_healthy
      scylla-node2:
        condition: service_healthy
      scylla-node3:
        condition: service_healthy
      kafka:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build: ./Frontend/my-app
    ports:
      - "5001:5001"
    depends_on:
      - log-ingestor
      - query-interface
    networks:
      - custom_network

volumes:
  scylla-data1:
  scylla-data2:
  scylla-data3:
  scylla-commitlog1:
  scylla-commitlog2:
  scylla-commitlog3:
  postgres-data:
  elasticsearch-data:

networks:
  custom_network:
    driver: bridge